version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - sebbo2002
    commit-message:
      prefix: "ci"
      include: scope
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 1
    assignees:
      - sebbo2002
    commit-message:
      prefix: "build"
      prefix-development: "chore"
      include: scope
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    assignees:
      - sebbo2002
    commit-message:
      prefix: "build"
    schedule:
      interval: weekly

