name: ReleaseBot
on:
  workflow_dispatch:
  push:
    branches: ['develop']
  schedule:
    - cron: '30 8 * * 3'

jobs:
  release-bot:
    runs-on: ubuntu-latest
    steps:
      - name: ☁️ Checkout Project
        uses: actions/checkout@v2
      - name: 🤖 Run ReleaseBot
        uses: sebbo2002/release-bot@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
